local util = require("util")
util.map("n", "<leader>wt", "<cmd>Neotree float<CR>")
util.map("n", "<leader>wT", "<cmd>Neotree float reveal_file=%<CR>")
vim.cmd("hi NeoTreeTitleBar guifg='#FFFFFF'")
--vim.keymap.set("n", "<leader>J", require("nvim-tree.api").marks.navigate.next)
--vim.keymap.set("n", "<leader>K", require("nvim-tree.api").marks.navigate.prev)
--vim.keymap.set("n", "<leader>ts", require("nvim-tree.api").marks.navigate.select)
